### ISSUE TITLE
Gradient overlay

### ISSUE THREAD

**Issue by btxtiger** [nk-crew/awb#44]
Would be great to have the gradient overlay supported, like in the WordPress default "Cover" Block, additionally to linear color.

![image](https://user-images.githubusercontent.com/15804690/113357534-6ff02380-9344-11eb-9f04-209f65dc519d.png)

**Comment by nk-o** [comment]
Hey. This feature will only be in the Pro plugin, which we not yet working on https://github.com/nk-crew/awb/issues/2
