### ISSUE TITLE
New Vimeo Play/Pause button showing...

### ISSUE THREAD

**Issue by josh-jeffrey** [nk-crew/awb#56]
It looks like Vimeo may have added a new element of an embedded play/pause button (gray button) when the background videos start, loop, or on scroll. Just noticed this across our websites that use AWB. Wondering if there's a new option to disable this as it's showing up in background videos, and is unclickable due to the z-index I believe. 

Attached screenshot of the button that shows on scroll up / loop / on-load.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/29985471/199332976-31a31560-304e-4a5b-b7c4-be6771301573.png">

**Comment by nk-o** [comment]
Hey.

As per Vimeo guidelines, the Padi plan is required to hide the play button - https://vimeo.zendesk.com/hc/en-us/articles/115011183028-Embed-background-and-chromeless-videos

Regards, nK.
