### ISSUE TITLE
One of my two WordPress sites suddenly no longer supports AWB - Help!

### ISSUE THREAD

**Issue by rhst1** [nk-crew/awb#63]
One of my two WordPress sites suddenly no longer supports AWB - Help! 

The site that works normally is https://wakarusariver.com

The site that just stopped working is https://fixyourbusinessyourself.org

They are both hosted by the same service and I believe have all the same basic settings.

I've attached one image that shows the error message:

![awberror](https://github.com/nk-crew/awb/assets/55596872/793c83af-520f-41cc-9c2e-75362a427036)

And a second image showing that AWB is installed and activated

![awbinstalled](https://github.com/nk-crew/awb/assets/55596872/6ba885fe-cfea-48ad-b486-8f4af9ded09d)

Thanks for your help!

PS I have clicked the Install Background (AWB) blue button in the error message, but it doesn't fix anything.

Things I've checked (none of which fixed the problem):

1) deactivated and reactivated AWB
2) compared versions of WordPress, database, etc. between the two sites, everything I've checked is identical
3) deleted plug-ins that thought might cause conflict

**Comment by rhst1** [comment]
PS I have clicked the Install Background (AWB) blue button in the error message, but it doesn't fix anything.

**Comment by tambaqui** [comment]
Hi, same here after updating WordPress to version 6.4.1. The AWB Gutenberg Block has stopped working. 
Throws an error in console:
`Uncaught TypeError: Cannot destructure property ‘compact’ of ‘window.lodash’ as it is undefined.`

**Comment by rhst1** [comment]
Hopefully AWB or someone else who knows how to fix these issues will respond soon. I've also reported my problem at the WordPress.org support forum, but have had no comments there, yet.

I'm testing an alternative plugin to AWB, that I may have to use instead. It's called Parallax Section - Block by bPlugins LLC

**Comment by tambaqui** [comment]
Hello, the quick solution that I have applied in my local installation is to add lodash as. dependency:
In file advanced-backgrounds/classes/class-gutenberg.php, line 37, chage:

`$js_deps  = array( 'wp-i18n', 'wp-element', 'wp-components', 'wp-block-editor', 'underscore', 'jquery', 'jarallax', 'jarallax-video' );`

By:

`$js_deps  = array( 'wp-i18n', 'wp-element', 'wp-components', 'wp-block-editor', 'underscore', 'jquery', 'jarallax', 'jarallax-video', 'lodash' );`

I hope they can fix it soon in the official plugin.

**Comment by rhst1** [comment]
Thanks, tambaqui

I tried adding lodash and it made the errors on the WordPress editing page go away, but after saving the changes the actual page is still not functioning correctly.

I also looked at the code on the website that is working normally for me and saw that there is no lodash on line 37.

**Comment by tambaqui** [comment]
Ok @rhst1. 
Probably the website that works without the lodash dependency is already loading it in another way, either because it is an older version of WordPress that already loads lodash by default in the editor or because another plugin is loading it secondary.
In any case AWB has that dependency, so if it is not available by default, it must be indicated in the list of dependencies.

**Comment by nk-o** [comment]
Hi guys. Thank you for reporting to me. The plugin will be updated with a quick fix soon.

**Comment by rhst1** [comment]
Excellent!
